apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 99-motd-workers
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
      - contents:
          #source: data:text/plain;charset=utf-8;base64,4paR4paS4paT4paI4paT4paS4paR4paR4paS4paT4paI4paT4paS4paR4paS4paT4paI4paI4paI4paI4paI4paI4paI4paI4paT4paS4paR4paS4paT4paI4paT4paS4paRICAgICAg4paR4paS4paT4paI4paT4paS4paRICAgICAg4paR4paS4paT4paI4paI4paI4paI4paI4paI4paT4paS4paRICAK4paR4paS4paT4paI4paT4paS4paR4paR4paS4paT4paI4paT4paS4paR4paS4paT4paI4paT4paS4paRICAgICAg4paR4paS4paT4paI4paT4paS4paRICAgICAg4paR4paS4paT4paI4paT4paS4paRICAgICDilpHilpLilpPilojilpPilpLilpHilpHilpLilpPilojilpPilpLilpEgCuKWkeKWkuKWk+KWiOKWk+KWkuKWkeKWkeKWkuKWk+KWiOKWk+KWkuKWkeKWkuKWk+KWiOKWk+KWkuKWkSAgICAgIOKWkeKWkuKWk+KWiOKWk+KWkuKWkSAgICAgIOKWkeKWkuKWk+KWiOKWk+KWkuKWkSAgICAg4paR4paS4paT4paI4paT4paS4paR4paR4paS4paT4paI4paT4paS4paRIArilpHilpLilpPilojilojilojilojilojilojilojilojilpPilpLilpHilpLilpPilojilojilojilojilojilojilpPilpLilpEg4paR4paS4paT4paI4paT4paS4paRICAgICAg4paR4paS4paT4paI4paT4paS4paRICAgICDilpHilpLilpPilojilpPilpLilpHilpHilpLilpPilojilpPilpLilpEgCuKWkeKWkuKWk+KWiOKWk+KWkuKWkeKWkeKWkuKWk+KWiOKWk+KWkuKWkeKWkuKWk+KWiOKWk+KWkuKWkSAgICAgIOKWkeKWkuKWk+KWiOKWk+KWkuKWkSAgICAgIOKWkeKWkuKWk+KWiOKWk+KWkuKWkSAgICAg4paR4paS4paT4paI4paT4paS4paR4paR4paS4paT4paI4paT4paS4paRIArilpHilpLilpPilojilpPilpLilpHilpHilpLilpPilojilpPilpLilpHilpLilpPilojilpPilpLilpEgICAgICDilpHilpLilpPilojilpPilpLilpEgICAgICDilpHilpLilpPilojilpPilpLilpEgICAgIOKWkeKWkuKWk+KWiOKWk+KWkuKWkeKWkeKWkuKWk+KWiOKWk+KWkuKWkSAK4paR4paS4paT4paI4paT4paS4paR4paR4paS4paT4paI4paT4paS4paR4paS4paT4paI4paI4paI4paI4paI4paI4paI4paI4paT4paS4paR4paS4paT4paI4paI4paI4paI4paI4paI4paI4paI4paT4paS4paR4paS4paT4paI4paI4paI4paI4paI4paI4paI4paI4paT4paS4paR4paS4paT4paI4paI4paI4paI4paI4paI4paT4paS4paRCg==
          source: https://raw.githubusercontent.com/kharyam/go-litra-driver/refs/heads/main/README.md
        mode: 420
        overwrite: true
        path: /etc/motd
