apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
    app.kubernetes.io/instance: motd
  name: 99-master-motd
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,CiMgICAgICMgICMjIyMjIyMgICMgICAgICAgICMgICAgICAgICMjIyMjIyMgIAojICAgICAjICAjICAgICAgICAjICAgICAgICAjICAgICAgICAjICAgICAjICAKIyAgICAgIyAgIyAgICAgICAgIyAgICAgICAgIyAgICAgICAgIyAgICAgIyAgCiMjIyMjIyMgICMjIyMjICAgICMgICAgICAgICMgICAgICAgICMgICAgICMgIAojICAgICAjICAjICAgICAgICAjICAgICAgICAjICAgICAgICAjICAgICAjICAKIyAgICAgIyAgIyAgICAgICAgIyAgICAgICAgIyAgICAgICAgIyAgICAgIyAgCiMgICAgICMgICMjIyMjIyMgICMjIyMjIyMgICMjIyMjIyMgICMjIyMjIyMgIAoK
        mode: 420
        overwrite: true
        path: /etc/motd
