apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: motd
  namespace: openshift-gitops
spec:
  destination:
    name: in-cluster
  project: default
  source:
    path: .
    repoURL: https://github.com/kharyam/motd.git
    targetRevision: HEAD
